version: "3.6"
services:
    api:
        build: .
        container_name: api
        entrypoint: npm run dev
        env_file:
            - .env
        environment:
            - API_PORT=${API_PORT}
        ports:
            - "${API_PORT}:${API_PORT}"
        depends_on:
            - db
        links:
            - db
        volumes:
            - type: bind
              source: ./src
              target: /api/src
        tty: true
        stdin_open: true
    db:
        image: postgres:12.2-alpine
        container_name: db
        expose:
            - 5432
        env_file:
            - .env
        environment:
            - PGDATA=/var/lib/data/postgresql/data/pgdata
        volumes:
            - ./data/pg:/var/lib/postgresql/data
    nginx:
        image: nginx:1.17-alpine
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - api
        links:
            - api
        volumes:
            - ./data/nginx:/etc/nginx/conf.d
            - ./data/cert:/etc/cert
